name: publish-build
on: push
jobs:
  publish-latest-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: set env vars
        run: |
          echo "VERSION=$(jq -r '.version' public/manifest.json)" >> $GITHUB_ENV
          echo "FILENAME=$(v$VERSION.zip)" >> $GITHUB_ENV
          echo $VERSION
          echo $FILENAME
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: compare-version
        run: |
          cv=$(git tag | head)
          if [ "$cv" = v"$VERSION" ]; then
            exit 1
          fi
      - run: npm ci
      - run: CI=false npm run build
      - run: zip -r $FILENAME build
      - name: create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: ${{ env.VERSION }}
          files: ${{ env.FILENAME }}
      - name: publish to web store
        uses: mnao305/chrome-extension-upload@1.1.1
        with:
          file-path: ${{ env.FILENAME }}
          extension-id: "bhibdhiabdiojelgbfgfoflfkjmgfdop"
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
